runtime: python39
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

handlers:
- url: /.*
  script: auto
  secure: always

includes:
- src/**

# Add this to skip files we don't want to deploy
skip_files:
- ^(.*/)?\..*$
- ^(.*/)?.*\.pyc$
- ^(.*/)?.*\.pyo$
- ^(.*/)?.*\.pyd$
- ^(.*/)?.*_test\.py$
- ^(.*/)?.*\.md$