runtime: python39
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

handlers:
- url: /static
  static_dir: src/static
  secure: always

- url: /.*
  script: auto
  secure: always

env_variables:
  PYTHONPATH: "/workspace:${PYTHONPATH}"
  DB_USER: "app_user"
  DB_PASSWORD: "9pQK?fJF.9Lm]nv;"
  DB_NAME: "modernity_survey"
  INSTANCE_CONNECTION_NAME: "modernity-worldview:us-central1:modernity-db"