runtime: python39
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

handlers:
- url: /.*
  script: auto
  secure: always

# Make includes more explicit
includes:
- src/
- src/data/
- src/data/questions_responses.json
- src/data/response_templates.json

skip_files:
- ^(.*/)?\..*$
- ^(.*/)?.*\.pyc$
- ^(.*/)?.*\.pyo$
- ^(.*/)?.*\.pyd$
- ^(.*/)?.*_test\.py$
- ^(.*/)?.*\.md$

env_variables:
  PYTHONPATH: "/workspace:${PYTHONPATH}"