runtime: python39
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

handlers:
# Add static files handler
- url: /static
  static_dir: src/static
  secure: always

- url: /.*
  script: auto
  secure: always

env_variables:
  PYTHONPATH: "/workspace:${PYTHONPATH}"