runtime: python39
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

handlers:
- url: /.*
  script: auto
  secure: always

skip_files:
- ^(.*/)?\..*$
- ^(.*/)?.*\.pyc$
- ^(.*/)?.*\.pyo$
- ^(.*/)?.*\.pyd$
- ^(.*/)?.*_test\.py$
- ^(.*/)?.*\.md$

env_variables:
  PYTHONPATH: "/workspace:${PYTHONPATH}"